# Generated by Django 5.2.3 on 2025-07-04 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronomical_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eclipse',
            name='obscuration_percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
