# Generated by Django 5.2.3 on 2025-06-18 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronomical_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SunData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sunrise', models.TimeField()),
                ('sunset', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='astronomical_events.location')),
            ],
        ),
    ]
