# Generated by Django 5.2.3 on 2025-06-16 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronomical_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteorShower',
            fields=[
                ('celestialevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='astronomical_events.celestialevent')),
                ('zhr', models.FloatField(blank=True, help_text='Zenithal Hourly Rate', null=True)),
                ('peak_date_time', models.DateTimeField(blank=True, null=True)),
                ('radiant_ra', models.FloatField(blank=True, help_text='Radiant Right Ascension (degrees)', null=True)),
                ('radiant_dec', models.FloatField(blank=True, help_text='Radiant Declination (degrees)', null=True)),
                ('duration_days', models.FloatField(blank=True, help_text='Active duration in days', null=True)),
                ('parent_body', models.CharField(blank=True, help_text='Comet or asteroid source', max_length=100)),
                ('velocity_kms', models.FloatField(blank=True, help_text='Meteor velocity in km/s', null=True)),
                ('magnitude_min', models.FloatField(blank=True, help_text='Minimum visible magnitude', null=True)),
                ('magnitude_max', models.FloatField(blank=True, help_text='Maximum visible magnitude', null=True)),
            ],
            options={
                'db_table': 'meteor_shower_events',
            },
            bases=('astronomical_events.celestialevent',),
        ),
    ]
