# Generated by Django 5.2.3 on 2025-06-16 05:49

import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronomical_events', '0002_meteorshower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(default='dsjd@outlook.com', max_length=254, unique=True),
        ),
    ]
