# Generated by Django 5.2.3 on 2025-07-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronomical_events', '0002_alter_eclipse_obscuration_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eclipse',
            name='path_coordinates',
        ),
        migrations.AddField(
            model_name='eclipse',
            name='partial_begin_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eclipse',
            name='partial_end_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eclipse',
            name='peak_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eclipse',
            name='total_begin_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eclipse',
            name='total_end_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
