# Generated by Django 5.2.3 on 2025-06-16 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronomical_events', '0003_alter_location_timezone_alter_subscription_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisibilityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=False)),
                ('rise_time', models.DateTimeField(blank=True, null=True)),
                ('set_time', models.DateTimeField(blank=True, null=True)),
                ('best_viewing_start', models.DateTimeField(blank=True, null=True)),
                ('best_viewing_end', models.DateTimeField(blank=True, null=True)),
                ('weather_conditions', models.CharField(blank=True, max_length=200)),
                ('light_pollution_level', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('celestial_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibility_details', to='astronomical_events.celestialevent')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astronomical_events.location')),
            ],
            options={
                'unique_together': {('celestial_event', 'location')},
            },
        ),
    ]
