# Generated by Django 5.2.3 on 2025-07-04 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronomical_events', '0003_remove_eclipse_path_coordinates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarthPosition',
            fields=[
                ('celestialevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='astronomical_events.celestialevent')),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('time', models.TimeField(help_text='Time in UTC format (HH:MM)')),
                ('phenomenon', models.CharField(choices=[('Perihelion', 'Perihelion - Closest to Sun'), ('Aphelion', 'Aphelion - Farthest from Sun'), ('Equinox', 'Equinox - Equal Day and Night'), ('Solstice', 'Solstice - Longest/Shortest Day')], max_length=20)),
                ('api_version', models.CharField(default='4.0.1', max_length=10)),
            ],
            options={
                'db_table': 'earth_positions',
                'ordering': ['date_time'],
                'indexes': [models.Index(fields=['year', 'phenomenon'], name='earth_posit_year_073663_idx')],
                'unique_together': {('year', 'phenomenon')},
            },
            bases=('astronomical_events.celestialevent',),
        ),
    ]
