# Generated by Django 5.2.3 on 2025-06-16 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronomical_events', '0004_visibilitydetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_images',
            },
        ),
        migrations.DeleteModel(
            name='AstronomyPicture',
        ),
        migrations.AlterField(
            model_name='celestialevent',
            name='importance_level',
            field=models.IntegerField(choices=[(1, 'Minor'), (2, 'Significant'), (3, 'Major'), (4, 'Critical')], default=2),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='celestial_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='astronomical_events.celestialevent'),
        ),
    ]
