# Generated by Django 5.2.3 on 2025-07-04 19:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronomical_events', '0004_earthposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarthOrbitEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phenom', models.CharField(choices=[('Perihelion', 'Perihelion'), ('Aphelion', 'Aphelion'), ('March Equinox', 'March Equinox'), ('June Solstice', 'June Solstice'), ('September Equinox', 'September Equinox'), ('December Solstice', 'December Solstice')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('distance_million_km', models.FloatField()),
                ('orbital_speed_km_s', models.FloatField()),
                ('solar_irradiance_w_m2', models.FloatField()),
                ('eccentricity', models.FloatField()),
                ('heliocentric_longitude', models.FloatField()),
                ('true_anomaly', models.FloatField()),
                ('solar_declination', models.FloatField()),
                ('longitude_of_perihelion', models.FloatField()),
                ('day_length_hours', models.FloatField(help_text='Day length at equator')),
                ('season', models.CharField(max_length=20)),
                ('overview', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'earth_orbit_events',
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='EarthPosition',
        ),
    ]
