# Generated by Django 5.2.3 on 2025-07-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astronomical_events', '0005_earthorbitevent_delete_earthposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earthorbitevent',
            name='longitude_of_perihelion',
        ),
    ]
