# Generated by Django 5.2.3 on 2025-06-16 06:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronomical_events', '0005_eventimage_delete_astronomypicture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(db_index=True)),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-3 country code', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True, help_text='Whether this is a public/national holiday')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'holidays',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='holidays_date_c1d23c_idx'), models.Index(fields=['country_code'], name='holidays_country_8bd7e3_idx')],
                'unique_together': {('date', 'country_code')},
            },
        ),
    ]
