# Generated by Django 5.2.3 on 2025-07-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronomical_events', '0006_remove_earthorbitevent_longitude_of_perihelion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celestialevent',
            name='event_type',
            field=models.CharField(choices=[('moon_phase', 'Moon Phase'), ('eclipse', 'Eclipse'), ('meteor_shower', 'Meteor Shower'), ('planetary_event', 'Planetary Event'), ('sunrise_sunset', 'Sunrise/Sunset'), ('astronomical_twilight', 'Astronomical Twilight'), ('conjunction', 'Conjunction'), ('opposition', 'Opposition'), ('moon_apogee', 'Moon Apogee'), ('moon_perigee', 'Moon Perigee')], max_length=50),
        ),
    ]
