# Generated by Django 5.2.3 on 2025-06-16 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronomical_events', '0006_holiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isspass',
            name='celestialevent_ptr',
        ),
        migrations.AlterModelOptions(
            name='celestialevent',
            options={'ordering': ['date_time']},
        ),
        migrations.RemoveField(
            model_name='celestialevent',
            name='visibility_info',
        ),
        migrations.AddField(
            model_name='celestialevent',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='celestialevent',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='celestialevent',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='celestialevent',
            name='viewing_difficulty',
            field=models.CharField(choices=[('easy', 'Easy - Naked Eye'), ('moderate', 'Moderate - Binoculars'), ('difficult', 'Difficult - Telescope Required'), ('expert', 'Expert - Advanced Equipment')], default='easy', max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='elevation_meters',
            field=models.IntegerField(default=0, help_text='Elevation above sea level in meters'),
        ),
        migrations.AddField(
            model_name='location',
            name='light_pollution_level',
            field=models.IntegerField(default=5, help_text='Bortle scale: 1=excellent dark sky, 9=inner city sky', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='planetaryevent',
            name='declination',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planetaryevent',
            name='elongation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planetaryevent',
            name='right_ascension',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='celestialevent',
            name='event_type',
            field=models.CharField(choices=[('moon_phase', 'Moon Phase'), ('eclipse', 'Eclipse'), ('meteor_shower', 'Meteor Shower'), ('planetary_event', 'Planetary Event'), ('sunrise_sunset', 'Sunrise/Sunset'), ('astronomical_twilight', 'Astronomical Twilight'), ('conjunction', 'Conjunction'), ('opposition', 'Opposition')], max_length=50),
        ),
        migrations.AlterField(
            model_name='eclipse',
            name='obscuration_percentage',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='moonphase',
            name='illumination_percentage',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddIndex(
            model_name='celestialevent',
            index=models.Index(fields=['importance_level', 'date_time'], name='celestial_e_importa_1c6b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='celestialevent',
            index=models.Index(fields=['is_featured'], name='celestial_e_is_feat_669933_idx'),
        ),
        migrations.DeleteModel(
            name='ISSPass',
        ),
    ]
